require "Fishing/fishing_properties"

local AFDorado = {};
AFDorado.name = "Dorado";
AFDorado.item = "AdvancedFishing.Dorado";
AFDorado.lure = {};
table.insert(AFDorado.lure, "StormFlutterstick");
table.insert(AFDorado.lure, "RattlinRap");
table.insert(AFDorado.lure, "Spinnerbait");
table.insert(AFDorado.lure, "SpoonLure2");
table.insert(AFDorado.lure, "DentMediumfloaterline");
table.insert(AFDorado.lure, "DentMediumdeepline");
table.insert(AFDorado.lure, "PejeMediumdeepline");
table.insert(AFDorado.lure, "MouseBigfloaterline");
table.insert(AFDorado.lure, "TurtleMediumdeepline");
table.insert(AFDorado.lure, "Anguila");
table.insert(AFDorado.lure, "AngMediumfloaterline");
AFDorado.little = {};
AFDorado.medium = {};
AFDorado.big = {};
AFDorado.trophy = {};
AFDorado.little.minSize = 25;
AFDorado.little.maxSize = 40;
AFDorado.little.scale = 0.6;
AFDorado.medium.minSize = 40;
AFDorado.medium.maxSize = 80;
AFDorado.medium.scale = 0.8;
AFDorado.big.minSize = 80;
AFDorado.big.maxSize = 100;
AFDorado.big.scale = 1.0;
AFDorado.trophy.minSize = 100;
AFDorado.trophy.maxSize = 110;
AFDorado.trophy.scale = 1.1;
AFDorado.little.weightChange = 23;
AFDorado.medium.weightChange = 18;
AFDorado.big.weightChange = 12;
AFDorado.trophy.weightChange = 10;
table.insert(fishes, AFDorado);

local AFPacu = {};
AFPacu.name = "Pacu";
AFPacu.item = "AdvancedFishing.Pacu";
AFPacu.lure = {};
table.insert(AFPacu.lure, "PeachMediumdeepline");
AFPacu.little = {};
AFPacu.medium = {};
AFPacu.big = {};
AFPacu.trophy = {};
AFPacu.little.minSize = 25;
AFPacu.little.maxSize = 40;
AFPacu.little.scale = 0.6;
AFPacu.medium.minSize = 40;
AFPacu.medium.maxSize = 80;
AFPacu.medium.scale = 0.8;
AFPacu.big.minSize = 80;
AFPacu.big.maxSize = 100;
AFPacu.big.scale = 1.0;
AFPacu.trophy.minSize = 100;
AFPacu.trophy.maxSize = 110;
AFPacu.trophy.scale = 1.2;
AFPacu.little.weightChange = 50;
AFPacu.medium.weightChange = 40;
AFPacu.big.weightChange = 30;
AFPacu.trophy.weightChange = 25;
table.insert(fishes, AFPacu);

local AFPiranha = {};
AFPiranha.name = "Piranha";
AFPiranha.item = "AdvancedFishing.Piranha";
AFPiranha.lure = {};
table.insert(AFPiranha.lure, "SilkMothCaterpillar");
table.insert(AFPiranha.lure, "SwallowtailCaterpillar");
table.insert(AFPiranha.lure, "MonarchCaterpillar");
table.insert(AFPiranha.lure, "AmericanLadyCaterpillar");
table.insert(AFPiranha.lure, "BandedWoolyBearCaterpillar");
table.insert(AFPiranha.lure, "Centipede");
table.insert(AFPiranha.lure, "Centipede2");
table.insert(AFPiranha.lure, "Maggots");
table.insert(AFPiranha.lure, "Millipede");
table.insert(AFPiranha.lure, "Millipede2");
table.insert(AFPiranha.lure, "Pillbug");
table.insert(AFPiranha.lure, "SawflyLarva");
table.insert(AFPiranha.lure, "Slug");
table.insert(AFPiranha.lure, "Slug2");
table.insert(AFPiranha.lure, "Snail");
table.insert(AFPiranha.lure, "Termites");
table.insert(AFPiranha.lure, "StormFlutterstick");
table.insert(AFPiranha.lure, "RattlinRap");
table.insert(AFPiranha.lure, "SwimJig");
table.insert(AFPiranha.lure, "SwimJig2");
table.insert(AFPiranha.lure, "SwimJig3");
table.insert(AFPiranha.lure, "SpoonLure1");
table.insert(AFPiranha.lure, "SpoonLure2");
table.insert(AFPiranha.lure, "SpoonLure3");
table.insert(AFPiranha.lure, "Crankbait");
table.insert(AFPiranha.lure, "SwimShad");
table.insert(AFPiranha.lure, "Alfers");
table.insert(AFPiranha.lure, "Worm");
table.insert(AFPiranha.lure, "RedWorm");
table.insert(AFPiranha.lure, "WormSmallfloaterline");
table.insert(AFPiranha.lure, "Cricket");
table.insert(AFPiranha.lure, "CricketSmallfloaterline");
table.insert(AFPiranha.lure, "Grasshopper");
table.insert(AFPiranha.lure, "GHopperSmallfloaterline");
table.insert(AFPiranha.lure, "Cockroach");
table.insert(AFPiranha.lure, "RoachSmallfloaterline");
table.insert(AFPiranha.lure, "BaitFish");
table.insert(AFPiranha.lure, "BfishSmallfloaterline");
table.insert(AFPiranha.lure, "WturtlePiece");
table.insert(AFPiranha.lure, "CricketSmalldeepline");
table.insert(AFPiranha.lure, "WormSmalldeepline");
table.insert(AFPiranha.lure, "RWormSmalldeepline");
table.insert(AFPiranha.lure, "GHopperSmalldeepline");
table.insert(AFPiranha.lure, "RoachSmalldeepline");
table.insert(AFPiranha.lure, "BfishSmalldeepline");
AFPiranha.little = {};
AFPiranha.medium = {};
AFPiranha.big = {};
AFPiranha.trophy = {};
AFPiranha.little.minSize = 5;
AFPiranha.little.maxSize = 10;
AFPiranha.little.scale = 0.85;
AFPiranha.medium.minSize = 10;
AFPiranha.medium.maxSize = 20;
AFPiranha.medium.scale = 0.9;
AFPiranha.big.minSize = 20;
AFPiranha.big.maxSize = 35;
AFPiranha.big.scale = 1.0;
AFPiranha.trophy.minSize = 35;
AFPiranha.trophy.maxSize = 40;
AFPiranha.trophy.scale = 1.2;
AFPiranha.little.weightChange = 70;
AFPiranha.medium.weightChange = 60;
AFPiranha.big.weightChange = 50;
AFPiranha.trophy.weightChange = 45;
table.insert(fishes, AFPiranha);

local AFPalometa = {};
AFPalometa.name = "Palometa";
AFPalometa.item = "AdvancedFishing.Palometa";
AFPalometa.lure = {};
table.insert(AFPalometa.lure, "SilkMothCaterpillar");
table.insert(AFPalometa.lure, "SwallowtailCaterpillar");
table.insert(AFPalometa.lure, "MonarchCaterpillar");
table.insert(AFPalometa.lure, "AmericanLadyCaterpillar");
table.insert(AFPalometa.lure, "BandedWoolyBearCaterpillar");
table.insert(AFPalometa.lure, "Centipede");
table.insert(AFPalometa.lure, "Centipede2");
table.insert(AFPalometa.lure, "Maggots");
table.insert(AFPalometa.lure, "Millipede");
table.insert(AFPalometa.lure, "Millipede2");
table.insert(AFPalometa.lure, "Pillbug");
table.insert(AFPalometa.lure, "SawflyLarva");
table.insert(AFPalometa.lure, "Slug");
table.insert(AFPalometa.lure, "Slug2");
table.insert(AFPalometa.lure, "Snail");
table.insert(AFPalometa.lure, "Termites");
table.insert(AFPalometa.lure, "StormFlutterstick");
table.insert(AFPalometa.lure, "RattlinRap");
table.insert(AFPalometa.lure, "SwimJig");
table.insert(AFPalometa.lure, "SwimJig2");
table.insert(AFPalometa.lure, "SwimJig3");
table.insert(AFPalometa.lure, "SpoonLure1");
table.insert(AFPalometa.lure, "SpoonLure2");
table.insert(AFPalometa.lure, "SpoonLure3");
table.insert(AFPalometa.lure, "Crankbait");
table.insert(AFPalometa.lure, "SwimShad");
table.insert(AFPalometa.lure, "Alfers");
table.insert(AFPalometa.lure, "Worm");
table.insert(AFPalometa.lure, "RedWorm");
table.insert(AFPalometa.lure, "WormSmallfloaterline");
table.insert(AFPalometa.lure, "Cricket");
table.insert(AFPalometa.lure, "CricketSmallfloaterline");
table.insert(AFPalometa.lure, "Grasshopper");
table.insert(AFPalometa.lure, "GHopperSmallfloaterline");
table.insert(AFPalometa.lure, "Cockroach");
table.insert(AFPalometa.lure, "RoachSmallfloaterline");
table.insert(AFPalometa.lure, "BaitFish");
table.insert(AFPalometa.lure, "BfishSmallfloaterline");
table.insert(AFPalometa.lure, "WturtlePiece");
table.insert(AFPalometa.lure, "CricketSmalldeepline");
table.insert(AFPalometa.lure, "WormSmalldeepline");
table.insert(AFPalometa.lure, "RWormSmalldeepline");
table.insert(AFPalometa.lure, "GHopperSmalldeepline");
table.insert(AFPalometa.lure, "RoachSmalldeepline");
table.insert(AFPalometa.lure, "BfishSmalldeepline");
AFPalometa.little = {};
AFPalometa.medium = {};
AFPalometa.big = {};
AFPalometa.trophy = {};
AFPalometa.little.minSize = 5;
AFPalometa.little.maxSize = 10;
AFPalometa.little.scale = 0.8;
AFPalometa.medium.minSize = 10;
AFPalometa.medium.maxSize = 20;
AFPalometa.medium.scale = 0.9;
AFPalometa.big.minSize = 20;
AFPalometa.big.maxSize = 40;
AFPalometa.big.scale = 1.0;
AFPalometa.trophy.minSize = 40;
AFPalometa.trophy.maxSize = 45;
AFPalometa.trophy.scale = 1.2;
AFPalometa.little.weightChange = 65;
AFPalometa.medium.weightChange = 55;
AFPalometa.big.weightChange = 45;
AFPalometa.trophy.weightChange = 40;
table.insert(fishes, AFPalometa);

local AFPayara = {};
AFPayara.name = "Payara";
AFPayara.item = "AdvancedFishing.Payara";
AFPayara.lure = {};
table.insert(AFPayara.lure, "StormFlutterstick");
table.insert(AFPayara.lure, "RattlinRap");
table.insert(AFPayara.lure, "SpoonLure1");
table.insert(AFPayara.lure, "SpoonLure3");
table.insert(AFPayara.lure, "Crankbait");
table.insert(AFPayara.lure, "Alfers");
table.insert(AFPayara.lure, "DentMediumfloaterline");
table.insert(AFPayara.lure, "AngMediumfloaterline");
table.insert(AFPayara.lure, "Anguila");
AFPayara.little = {};
AFPayara.medium = {};
AFPayara.big = {};
AFPayara.trophy = {};
AFPayara.little.minSize = 25;
AFPayara.little.maxSize = 40;
AFPayara.medium.minSize = 40;
AFPayara.medium.maxSize = 80;
AFPayara.big.minSize = 80;
AFPayara.big.maxSize = 90;
AFPayara.trophy.minSize = 90;
AFPayara.trophy.maxSize = 100;
AFPayara.little.weightChange = 40;
AFPayara.medium.weightChange = 30;
AFPayara.big.weightChange = 25;
AFPayara.trophy.weightChange = 20;
table.insert(fishes, AFPayara);

local carp = {};
carp.name = "Carp";
carp.item = "AdvancedFishing.Carp";
carp.lure = {};
table.insert(carp.lure, "Snail");
table.insert(carp.lure, "FishingDough");
table.insert(carp.lure, "StrongFishingDough");
table.insert(carp.lure, "DoughMediumfloaterline");
table.insert(carp.lure, "FDoughMediumfloaterline");
table.insert(carp.lure, "DoughMediumdeepline");
table.insert(carp.lure, "FDoughMediumdeepline");
carp.little = {};
carp.medium = {};
carp.big = {};
carp.trophy = {};
carp.little.minSize = 50;
carp.little.maxSize = 65;
carp.medium.minSize = 65;
carp.medium.maxSize = 90;
carp.big.minSize = 90;
carp.big.maxSize = 100;
carp.trophy.minSize = 100;
carp.trophy.maxSize = 120;
carp.little.weightChange = 23;
carp.medium.weightChange = 18;
carp.big.weightChange = 10;
carp.trophy.weightChange = 8;
table.insert(fishes, carp);

local dentudo = {};
dentudo.item = "AdvancedFishing.Dentudo";
dentudo.lure = {};
table.insert(dentudo.lure, "SilkMothCaterpillar");
table.insert(dentudo.lure, "SwallowtailCaterpillar");
table.insert(dentudo.lure, "MonarchCaterpillar");
table.insert(dentudo.lure, "AmericanLadyCaterpillar");
table.insert(dentudo.lure, "BandedWoolyBearCaterpillar");
table.insert(dentudo.lure, "Centipede");
table.insert(dentudo.lure, "Centipede2");
table.insert(dentudo.lure, "Maggots");
table.insert(dentudo.lure, "Millipede");
table.insert(dentudo.lure, "Millipede2");
table.insert(dentudo.lure, "Pillbug");
table.insert(dentudo.lure, "SawflyLarva");
table.insert(dentudo.lure, "Termites");
table.insert(dentudo.lure, "WormSmallfloaterline");
table.insert(dentudo.lure, "RWormSmallfloaterline");
table.insert(dentudo.lure, "CricketSmallfloaterline");
table.insert(dentudo.lure, "GHopperSmallfloaterline");
table.insert(dentudo.lure, "RoachSmallfloaterline");
table.insert(dentudo.lure, "BfishSmallfloaterline");
table.insert(dentudo.lure, "CricketSmalldeepline");
table.insert(dentudo.lure, "WormSmalldeepline");
table.insert(dentudo.lure, "RWormSmalldeepline");
table.insert(dentudo.lure, "GHopperSmalldeepline");
table.insert(dentudo.lure, "RoachSmalldeepline");
table.insert(dentudo.lure, "BfishSmalldeepline");
table.insert(fishes, dentudo);

local AFPeje = {};
AFPeje.name = "Pejerrey";
AFPeje.item = "AdvancedFishing.Peje";
AFPeje.lure = {};
table.insert(AFPeje.lure, "SawflyLarva");
table.insert(AFPeje.lure, "Maggots");
table.insert(AFPeje.lure, "RedWorm");
table.insert(AFPeje.lure, "RWormSmallfloaterline");
table.insert(AFPeje.lure, "RWormSmalldeepline");
table.insert(AFPeje.lure, "BfishSmalldeepline");
AFPeje.little = {};
AFPeje.medium = {};
AFPeje.big = {};
AFPeje.trophy = {};
AFPeje.little.minSize = 5;
AFPeje.little.maxSize = 10;
AFPeje.medium.minSize = 10;
AFPeje.medium.maxSize = 20;
AFPeje.big.minSize = 20;
AFPeje.big.maxSize = 30;
AFPeje.trophy.minSize = 30;
AFPeje.trophy.maxSize = 40;
AFPeje.little.weightChange = 65;
AFPeje.medium.weightChange = 55;
AFPeje.big.weightChange = 50;
AFPeje.trophy.weightChange = 45;
table.insert(fishes, AFPeje);

local AFRtrout = {};
AFRtrout.name = "Rainbowtrout";
AFRtrout.item = "AdvancedFishing.RainbowTrout";
AFRtrout.lure = {};
table.insert(AFRtrout.lure, "SawflyLarva");
table.insert(AFRtrout.lure, "Maggots");
table.insert(AFRtrout.lure, "SpoonLure1");
table.insert(AFRtrout.lure, "SpoonLure2");
table.insert(AFRtrout.lure, "SpoonLure3");
table.insert(AFRtrout.lure, "Spinnerbait");
table.insert(AFRtrout.lure, "DentMediumfloaterline");
table.insert(AFRtrout.lure, "BfishMediumfloaterline");
table.insert(AFRtrout.lure, "PejeBigfloaterline");
table.insert(AFRtrout.lure, "DentBigfloaterline");
AFRtrout.little = {};
AFRtrout.medium = {};
AFRtrout.big = {};
AFRtrout.trophy = {};
AFRtrout.little.minSize = 20;
AFRtrout.little.maxSize = 40;
AFRtrout.medium.minSize = 40;
AFRtrout.medium.maxSize = 80;
AFRtrout.big.minSize = 80;
AFRtrout.big.maxSize = 100;
AFRtrout.trophy.minSize = 100;
AFRtrout.trophy.maxSize = 120;
AFRtrout.little.weightChange = 23;
AFRtrout.medium.weightChange = 18;
AFRtrout.big.weightChange = 14;
AFRtrout.trophy.weightChange = 12;
table.insert(fishes, AFRtrout);

local AFSalmon = {};
AFSalmon.name = "Salmon";
AFSalmon.item = "AdvancedFishing.FSalmon";
AFSalmon.lure = {};
table.insert(AFSalmon.lure, "SawflyLarva");
table.insert(AFSalmon.lure, "Maggots");
table.insert(AFSalmon.lure, "SpoonLure1");
table.insert(AFSalmon.lure, "SpoonLure2");
table.insert(AFSalmon.lure, "SpoonLure3");
table.insert(AFSalmon.lure, "Spinnerbait");
table.insert(AFSalmon.lure, "DentMediumfloaterline");
table.insert(AFSalmon.lure, "PejeBigfloaterline");
table.insert(AFSalmon.lure, "DentBigfloaterline");
--table.insert(AFSalmon.lure, "GoldenHook");
AFSalmon.little = {};
AFSalmon.medium = {};
AFSalmon.big = {};
AFSalmon.trophy = {};
AFSalmon.little.minSize = 40;
AFSalmon.little.maxSize = 60;
AFSalmon.medium.minSize = 60;
AFSalmon.medium.maxSize = 100;
AFSalmon.big.minSize = 100;
AFSalmon.big.maxSize = 120;
AFSalmon.trophy.minSize = 120;
AFSalmon.trophy.maxSize = 150;
AFSalmon.little.weightChange = 23;
AFSalmon.medium.weightChange = 18;
AFSalmon.big.weightChange = 10;
AFSalmon.trophy.weightChange = 8;
table.insert(fishes, AFSalmon);

local AFRtcatf = {};
AFRtcatf.name = "Rtcatfish";
AFRtcatf.item = "AdvancedFishing.Rtcatfish";
AFRtcatf.spearcatch = "yes";
AFRtcatf.lure = {};
table.insert(AFRtcatf.lure, "DentBigfloaterline");
table.insert(AFRtcatf.lure, "PejeBigfloaterline");
table.insert(AFRtcatf.lure, "FrogBigfloaterline");
table.insert(AFRtcatf.lure, "CrabBigfloaterline");
table.insert(AFRtcatf.lure, "RatBigfloaterline");
table.insert(AFRtcatf.lure, "AngMediumdeepline");
table.insert(AFRtcatf.lure, "AngHeavydeepline");
table.insert(AFRtcatf.lure, "RatHeavydeepline");
table.insert(AFRtcatf.lure, "MouseHeavydeepline");
table.insert(AFRtcatf.lure, "FrogHeavydeepline");
AFRtcatf.little = {};
AFRtcatf.medium = {};
AFRtcatf.big = {};
AFRtcatf.trophy = {};
AFRtcatf.little.minSize = 60;
AFRtcatf.little.maxSize = 100;
AFRtcatf.medium.minSize = 100;
AFRtcatf.medium.maxSize = 150;
AFRtcatf.big.minSize = 150;
AFRtcatf.big.maxSize = 170;
AFRtcatf.trophy.minSize = 170;
AFRtcatf.trophy.maxSize = 180;
AFRtcatf.little.weightChange = 18;
AFRtcatf.medium.weightChange = 10;
AFRtcatf.big.weightChange = 6;
AFRtcatf.trophy.weightChange = 4;
table.insert(fishes, AFRtcatf);

local AFSuru = {};
AFSuru.name = "Surubi";
AFSuru.item = "AdvancedFishing.Surubi";
AFSuru.spearcatch = "yes";
AFSuru.lure = {};
table.insert(AFSuru.lure, "SwimShad");
table.insert(AFSuru.lure, "Crankbait");
table.insert(AFSuru.lure, "DentBigfloaterline");
table.insert(AFSuru.lure, "PejeBigfloaterline");
table.insert(AFSuru.lure, "CrabBigfloaterline");
table.insert(AFSuru.lure, "FrogBigfloaterline");
table.insert(AFSuru.lure, "MouseBigfloaterline");
table.insert(AFSuru.lure, "AngMediumdeepline");
table.insert(AFSuru.lure, "AngBigfloaterline");
table.insert(AFSuru.lure, "AngHeavydeepline");
table.insert(AFSuru.lure, "RatHeavydeepline");
table.insert(AFSuru.lure, "MouseHeavydeepline");
AFSuru.little = {};
AFSuru.medium = {};
AFSuru.big = {};
AFSuru.trophy = {};
AFSuru.little.minSize = 30;
AFSuru.little.maxSize = 70;
AFSuru.little.scale = 0.6;
AFSuru.medium.minSize = 70;
AFSuru.medium.maxSize = 100;
AFSuru.medium.scale = 0.8;
AFSuru.big.minSize = 100;
AFSuru.big.maxSize = 120;
AFSuru.big.scale = 1.0;
AFSuru.trophy.minSize = 120;
AFSuru.trophy.maxSize = 130;
AFSuru.trophy.scale = 1.1;
AFSuru.little.weightChange = 25;
AFSuru.medium.weightChange = 12;
AFSuru.big.weightChange = 9;
AFSuru.trophy.weightChange = 7;
table.insert(fishes, AFSuru);

local AFTara = {};
AFTara.name = "Tararira";
AFTara.item = "AdvancedFishing.Tararira";
AFTara.lure = {};
table.insert(AFTara.lure, "SilkMothCaterpillar");
table.insert(AFTara.lure, "SwallowtailCaterpillar");
table.insert(AFTara.lure, "MonarchCaterpillar");
table.insert(AFTara.lure, "AmericanLadyCaterpillar");
table.insert(AFTara.lure, "BandedWoolyBearCaterpillar");
table.insert(AFTara.lure, "Maggots");
table.insert(AFTara.lure, "Pillbug");
table.insert(AFTara.lure, "Slug");
table.insert(AFTara.lure, "Slug2");
table.insert(AFTara.lure, "Snail");
table.insert(AFTara.lure, "GTPopper");
table.insert(AFTara.lure, "JitterBug");
table.insert(AFTara.lure, "SwimJig2");
table.insert(AFTara.lure, "FrogBigfloaterline");
table.insert(AFTara.lure, "StormFlutterstick");
table.insert(AFTara.lure, "RattlinRap");
table.insert(AFTara.lure, "Spinnerbait");
table.insert(AFTara.lure, "SpoonLure2");
table.insert(AFTara.lure, "DentMediumfloaterline");
table.insert(AFTara.lure, "GHopperMediumfloaterline");
table.insert(AFTara.lure, "BfishMediumfloaterline");
table.insert(AFTara.lure, "RoachMediumfloaterline");
table.insert(AFTara.lure, "DentMediumdeepline");
table.insert(AFTara.lure, "PejeMediumdeepline");
table.insert(AFTara.lure, "MouseBigfloaterline");
table.insert(AFTara.lure, "WturtlePiece");
table.insert(AFTara.lure, "TurtleMediumdeepline");
table.insert(AFTara.lure, "Anguila");
table.insert(AFTara.lure, "AngMediumfloaterline");
AFTara.little = {};
AFTara.medium = {};
AFTara.big = {};
AFTara.trophy = {};
AFTara.little.minSize = 10;
AFTara.little.maxSize = 30;
AFTara.little.scale = 0.8;
AFTara.medium.minSize = 30;
AFTara.medium.maxSize = 50;
AFTara.medium.scale = 1.0;
AFTara.big.minSize = 50;
AFTara.big.maxSize = 60;
AFTara.big.scale = 1.2;
AFTara.trophy.minSize = 60;
AFTara.trophy.maxSize = 70;
AFTara.trophy.scale = 1.4;
AFTara.little.weightChange = 45;
AFTara.medium.weightChange = 30;
AFTara.big.weightChange = 25;
AFTara.trophy.weightChange = 20;
table.insert(fishes, AFTara);

local AFTucu = {};
AFTucu.name = "Tucunare";
AFTucu.item = "AdvancedFishing.Tucunare";
AFTucu.lure = {};
table.insert(AFTucu.lure, "StormFlutterstick");
table.insert(AFTucu.lure, "RattlinRap");
table.insert(AFTucu.lure, "Spinnerbait");
table.insert(AFTucu.lure, "SpoonLure2");
table.insert(AFTucu.lure, "DentMediumfloaterline");
table.insert(AFTucu.lure, "DentMediumdeepline");
table.insert(AFTucu.lure, "MouseBigfloaterline");
table.insert(AFTucu.lure, "TurtleMediumdeepline");
table.insert(AFTucu.lure, "Anguila");
table.insert(AFTucu.lure, "AngMediumfloaterline");
AFTucu.little = {};
AFTucu.medium = {};
AFTucu.big = {};
AFTucu.trophy = {};
AFTucu.little.minSize = 15;
AFTucu.little.maxSize = 30;
AFTucu.medium.minSize = 30;
AFTucu.medium.maxSize = 50;
AFTucu.big.minSize = 50;
AFTucu.big.maxSize = 60;
AFTucu.trophy.minSize = 60;
AFTucu.trophy.maxSize = 70;
AFTucu.little.weightChange = 35;
AFTucu.medium.weightChange = 25;
AFTucu.big.weightChange = 20;
AFTucu.trophy.weightChange = 18;
table.insert(fishes, AFTucu);

local AFGSnake = {};
AFGSnake.name = "Snakehead";
AFGSnake.item = "AdvancedFishing.Snakehead";
AFGSnake.lure = {};
table.insert(AFGSnake.lure, "StormFlutterstick");
table.insert(AFGSnake.lure, "RattlinRap");
table.insert(AFGSnake.lure, "Spinnerbait");
table.insert(AFGSnake.lure, "SpoonLure2");
table.insert(AFGSnake.lure, "DentMediumfloaterline");
table.insert(AFGSnake.lure, "RatBigfloaterline");
table.insert(AFGSnake.lure, "WturtlePiece");
table.insert(AFGSnake.lure, "DentMediumdeepline");
table.insert(AFGSnake.lure, "PejeMediumdeepline");
table.insert(AFGSnake.lure, "TurtleMediumdeepline");
table.insert(AFGSnake.lure, "Anguila");
table.insert(AFGSnake.lure, "AngMediumdeepline");
table.insert(AFGSnake.lure, "AngHeavydeepline");
AFGSnake.little = {};
AFGSnake.medium = {};
AFGSnake.big = {};
AFGSnake.trophy = {};
AFGSnake.little.minSize = 35;
AFGSnake.little.maxSize = 90;
AFGSnake.medium.minSize = 90;
AFGSnake.medium.maxSize = 130;
AFGSnake.big.minSize = 130;
AFGSnake.big.maxSize = 170;
AFGSnake.trophy.minSize = 170;
AFGSnake.trophy.maxSize = 180;
AFGSnake.little.weightChange = 35;
AFGSnake.medium.weightChange = 30;
AFGSnake.big.weightChange = 25;
AFGSnake.trophy.weightChange = 20;
table.insert(fishes, AFGSnake);

local AFPirai = {};
AFPirai.name = "Piraiba";
AFPirai.item = "AdvancedFishing.Piraiba";
AFPirai.spearcatch = "yes";
AFPirai.lure = {};
table.insert(AFPirai.lure, "DentBigfloaterline");
table.insert(AFPirai.lure, "PejeBigfloaterline");
table.insert(AFPirai.lure, "AngBigfloaterline");
--table.insert(AFPirai.lure, "GoldenHook");
table.insert(AFPirai.lure, "AngHeavydeepline");
table.insert(AFPirai.lure, "MouseHeavydeepline");
table.insert(AFPirai.lure, "FrogHeavydeepline");
AFPirai.little = {};
AFPirai.medium = {};
AFPirai.big = {};
AFPirai.trophy = {};
AFPirai.little.minSize = 60;
AFPirai.little.maxSize = 100;
AFPirai.medium.minSize = 100;
AFPirai.medium.maxSize = 150;
AFPirai.big.minSize = 150;
AFPirai.big.maxSize = 170;
AFPirai.trophy.minSize = 170;
AFPirai.trophy.maxSize = 180;
AFPirai.little.weightChange = 18;
AFPirai.medium.weightChange = 10;
AFPirai.big.weightChange = 5;
AFPirai.trophy.weightChange = 4;
table.insert(fishes, AFPirai);

local AFArp = {};
AFArp.name = "Arapaima";
AFArp.item = "AdvancedFishing.Arapaima";
AFArp.spearcatch = "yes";
AFArp.lure = {};
table.insert(AFArp.lure, "DentBigfloaterline");
table.insert(AFArp.lure, "PejeBigfloaterline");
table.insert(AFArp.lure, "AngBigfloaterline");
table.insert(AFArp.lure, "AngHeavydeepline");
table.insert(AFArp.lure, "MouseHeavydeepline");
--table.insert(AFArp.lure, "GoldenHook");
AFArp.little = {};
AFArp.medium = {};
AFArp.big = {};
AFArp.trophy = {};
AFArp.little.minSize = 60;
AFArp.little.maxSize = 120;
AFArp.medium.minSize = 120;
AFArp.medium.maxSize = 160;
AFArp.big.minSize = 160;
AFArp.big.maxSize = 210;
AFArp.trophy.minSize = 210;
AFArp.trophy.maxSize = 230;
AFArp.little.weightChange = 13;
AFArp.medium.weightChange = 5;
AFArp.big.weightChange = 4;
AFArp.trophy.weightChange = 2;
table.insert(fishes, AFArp);

local AFRay = {};
AFRay.name = "Ray";
AFRay.item = "AdvancedFishing.Ray";
AFRay.spearcatch = "yes";
AFRay.lure = {};
table.insert(AFRay.lure, "RatHeavydeepline");
table.insert(AFRay.lure, "FrogHeavydeepline");
AFRay.little = {};
AFRay.medium = {};
AFRay.big = {};
AFRay.trophy = {};
AFRay.little.minSize = 30;
AFRay.little.maxSize = 60;
AFRay.medium.minSize = 60;
AFRay.medium.maxSize = 70;
AFRay.big.minSize = 70;
AFRay.big.maxSize = 85;
AFRay.trophy.minSize = 85;
AFRay.trophy.maxSize = 95;
AFRay.little.weightChange = 13;
AFRay.medium.weightChange = 5;
AFRay.big.weightChange = 3;
AFRay.trophy.weightChange = 2;
table.insert(fishes, AFRay);

local AFTarpon = {};
AFTarpon.name = "Tarpon";
AFTarpon.item = "AdvancedFishing.Tarpon";
AFTarpon.spearcatch = "yes";
AFTarpon.lure = {};
table.insert(AFTarpon.lure, "DentBigfloaterline");
table.insert(AFTarpon.lure, "PejeBigfloaterline");
table.insert(AFTarpon.lure, "FrogBigfloaterline");
table.insert(AFTarpon.lure, "RatBigfloaterline");
table.insert(AFTarpon.lure, "MouseBigfloaterline");
table.insert(AFTarpon.lure, "AngBigfloaterline");
table.insert(AFTarpon.lure, "FrogHeavydeepline");
AFTarpon.little = {};
AFTarpon.medium = {};
AFTarpon.big = {};
AFTarpon.trophy = {};
AFTarpon.little.minSize = 60;
AFTarpon.little.maxSize = 100;
AFTarpon.medium.minSize = 100;
AFTarpon.medium.maxSize = 180;
AFTarpon.big.minSize = 180;
AFTarpon.big.maxSize = 220;
AFTarpon.trophy.minSize = 220;
AFTarpon.trophy.maxSize = 250;
AFTarpon.little.weightChange = 18;
AFTarpon.medium.weightChange = 10;
AFTarpon.big.weightChange = 5;
AFTarpon.trophy.weightChange = 4;
table.insert(fishes, AFTarpon);

local crab = {};
crab.item = "AdvancedFishing.Crab";
crab.lure = {};
table.insert(crab.lure, "Slug");
table.insert(crab.lure, "Slug2");
table.insert(crab.lure, "Snail");
table.insert(crab.lure, "RedWorm");
table.insert(crab.lure, "WturtlePiece");
table.insert(crab.lure, "BfishSmalldeepline");
table.insert(crab.lure, "DoughSmalldeepline");
table.insert(crab.lure, "FDoughSmalldeepline");
table.insert(crab.lure, "CricketSmalldeepline");
table.insert(crab.lure, "WormSmalldeepline");
table.insert(crab.lure, "RWormSmalldeepline");
table.insert(crab.lure, "GHopperSmalldeepline");
table.insert(crab.lure, "RoachSmalldeepline");
table.insert(crab.lure, "PeachMediumdeepline");
table.insert(crab.lure, "DoughMediumdeepline");
table.insert(crab.lure, "FDoughMediumdeepline");
table.insert(crab.lure, "TurtleMediumdeepline");
table.insert(fishes, crab);

local AFTurtle = {};
AFTurtle.name = "Turtle";
AFTurtle.item = "AdvancedFishing.Waterturtle";
AFTurtle.lure = {};
table.insert(AFTurtle.lure, "BaitFish");
table.insert(AFTurtle.lure, "PeachMediumdeepline");
table.insert(AFTurtle.lure, "DoughMediumdeepline");
table.insert(AFTurtle.lure, "FDoughMediumdeepline");
table.insert(AFTurtle.lure, "TurtleMediumdeepline");
table.insert(AFTurtle.lure, "MouseHeavydeepline");
AFTurtle.little = {};
AFTurtle.medium = {};
AFTurtle.big = {};
AFTurtle.trophy = {};
AFTurtle.little.minSize = 10;
AFTurtle.little.maxSize = 20;
AFTurtle.medium.minSize = 20;
AFTurtle.medium.maxSize = 35;
AFTurtle.big.minSize = 35;
AFTurtle.big.maxSize = 40;
AFTurtle.trophy.minSize = 40;
AFTurtle.trophy.maxSize = 45;
AFTurtle.little.weightChange = 70;
AFTurtle.medium.weightChange = 60;
AFTurtle.big.weightChange = 55;
AFTurtle.trophy.weightChange = 50;
table.insert(fishes, AFTurtle);

local pati = {};
pati.name = "Pati";
pati.item = "AdvancedFishing.Pati";
pati.lure = {};
table.insert(pati.lure, "DentMediumdeepline");
table.insert(pati.lure, "PejeMediumdeepline");
table.insert(pati.lure, "TurtleMediumdeepline");
table.insert(pati.lure, "AngMediumdeepline");
table.insert(pati.lure, "FrogHeavydeepline");
--table.insert(pati.lure, "GoldenHook");
pati.little = {};
pati.medium = {};
pati.big = {};
pati.trophy = {};
pati.little.minSize = 15;
pati.little.maxSize = 35;
pati.little.scale = 0.8;
pati.medium.minSize = 35;
pati.medium.maxSize = 80;
pati.medium.scale = 0.9;
pati.big.minSize = 80;
pati.big.maxSize = 110;
pati.big.scale = 1;
pati.trophy.minSize = 110;
pati.trophy.maxSize = 120;
pati.trophy.scale = 1.1;
pati.little.weightChange = 50;
pati.medium.weightChange = 40;
pati.big.weightChange = 32;
pati.trophy.weightChange = 30;
table.insert(fishes, pati);

local anguila = {};
anguila.name = "Anguila";
anguila.item = "AdvancedFishing.Anguila";
anguila.lure = {};
table.insert(anguila.lure, "Slug");
table.insert(anguila.lure, "Slug2");
table.insert(anguila.lure, "Snail");
table.insert(anguila.lure, "RedWorm");
table.insert(anguila.lure, "DentMediumdeepline");
table.insert(anguila.lure, "PejeMediumdeepline");
table.insert(anguila.lure, "TurtleMediumdeepline");
table.insert(anguila.lure, "DoughMediumdeepline");
table.insert(anguila.lure, "FDoughMediumdeepline");
table.insert(anguila.lure, "PeachMediumdeepline");
--table.insert(anguila.lure, "GoldenHook");
anguila.little = {};
anguila.medium = {};
anguila.big = {};
anguila.trophy = {};
anguila.little.minSize = 15;
anguila.little.maxSize = 70;
anguila.little.scale = 0.4;
anguila.medium.minSize = 70;
anguila.medium.maxSize = 120;
anguila.medium.scale = 0.6;
anguila.big.minSize = 120;
anguila.big.maxSize = 190;
anguila.big.scale = 0.8;
anguila.trophy.minSize = 190;
anguila.trophy.maxSize = 200;
anguila.trophy.scale = 1.0;
anguila.little.weightChange = 140;
anguila.medium.weightChange = 130;
anguila.big.weightChange = 120;
anguila.trophy.weightChange = 100;
table.insert(fishes, anguila);

local arowana = {};
arowana.name = "Arowana";
arowana.item = "AdvancedFishing.Arowana";
arowana.lure = {};
table.insert(arowana.lure, "DentMediumdeepline");
table.insert(arowana.lure, "PejeMediumdeepline");
table.insert(arowana.lure, "GTPopper");
table.insert(arowana.lure, "Alfers");
table.insert(arowana.lure, "StormFlutterstick");
table.insert(arowana.lure, "CricketSmallfloaterline");
table.insert(arowana.lure, "GHopperSmallfloaterline");
table.insert(arowana.lure, "RoachSmallfloaterline");
table.insert(arowana.lure, "BfishSmallfloaterline");
table.insert(arowana.lure, "Cricket");
table.insert(arowana.lure, "Grasshopper");
table.insert(arowana.lure, "Cockroach");
table.insert(arowana.lure, "BaitFish");
arowana.little = {};
arowana.medium = {};
arowana.big = {};
arowana.trophy = {};
arowana.little.minSize = 15;
arowana.little.maxSize = 60;
arowana.medium.minSize = 60;
arowana.medium.maxSize = 80;
arowana.big.minSize = 80;
arowana.big.maxSize = 100;
arowana.trophy.minSize = 100;
arowana.trophy.maxSize = 120;
arowana.little.weightChange = 50;
arowana.medium.weightChange = 45;
arowana.big.weightChange = 42;
arowana.trophy.weightChange = 40;
table.insert(fishes, arowana);

--Objetos

local lurebox = {};
lurebox.item = "AdvancedFishing.Fishinglurebox";
lurebox.lure = {};
table.insert(lurebox.lure, "SilkMothCaterpillar");
table.insert(lurebox.lure, "SwallowtailCaterpillar");
table.insert(lurebox.lure, "MonarchCaterpillar");
table.insert(lurebox.lure, "AmericanLadyCaterpillar");
table.insert(lurebox.lure, "BandedWoolyBearCaterpillar");
table.insert(lurebox.lure, "Centipede");
table.insert(lurebox.lure, "Centipede2");
table.insert(lurebox.lure, "Maggots");
table.insert(lurebox.lure, "Millipede");
table.insert(lurebox.lure, "Millipede2");
table.insert(lurebox.lure, "Pillbug");
table.insert(lurebox.lure, "SawflyLarva");
table.insert(lurebox.lure, "Slug");
table.insert(lurebox.lure, "Slug2");
table.insert(lurebox.lure, "Snail");
table.insert(lurebox.lure, "Termites");
table.insert(lurebox.lure, "0Smallfloaterline");
table.insert(lurebox.lure, "Mediumfloaterline");
table.insert(lurebox.lure, "Cricket");
table.insert(lurebox.lure, "Grasshopper");
table.insert(lurebox.lure, "Cockroach");
table.insert(lurebox.lure, "BaitFish");
table.insert(lurebox.lure, "Bigfloaterline");
table.insert(lurebox.lure, "DentBigfloaterline");
table.insert(lurebox.lure, "FrogBigfloaterline");
table.insert(lurebox.lure, "RatBigfloaterline");
table.insert(lurebox.lure, "MouseBigfloaterline");
table.insert(lurebox.lure, "CrabBigfloaterline");
table.insert(lurebox.lure, "PejeBigfloaterline");
table.insert(lurebox.lure, "SmallDeepline");
table.insert(lurebox.lure, "DoughSmalldeepline");
table.insert(lurebox.lure, "FDoughSmalldeepline");
table.insert(lurebox.lure, "CricketSmalldeepline");
table.insert(lurebox.lure, "WormSmalldeepline");
table.insert(lurebox.lure, "RWormSmalldeepline");
table.insert(lurebox.lure, "GHopperSmalldeepline");
table.insert(lurebox.lure, "RoachSmalldeepline");
table.insert(lurebox.lure, "BfishSmalldeepline");
table.insert(lurebox.lure, "MediumDeepline");
table.insert(lurebox.lure, "DentMediumdeepline");
table.insert(lurebox.lure, "PejeMediumdeepline");
table.insert(lurebox.lure, "PeachMediumdeepline");
table.insert(lurebox.lure, "DoughMediumdeepline");
table.insert(lurebox.lure, "FDoughMediumdeepline");
table.insert(lurebox.lure, "TurtleMediumdeepline");
table.insert(lurebox.lure, "AngMediumdeepline");
table.insert(lurebox.lure, "HeavyDeepline");
table.insert(trashItems, lurebox);

local rainboots = {};
rainboots.item = "Base.Shoes_Wellies";
rainboots.lure = {};
table.insert(rainboots.lure, "Mediumfloaterline");
table.insert(rainboots.lure, "WormMediumfloaterline");
table.insert(rainboots.lure, "DentMediumfloaterline");
table.insert(rainboots.lure, "RWormMediumfloaterline");
table.insert(rainboots.lure, "BfishMediumfloaterline");
table.insert(rainboots.lure, "RoachMediumfloaterline");
table.insert(rainboots.lure, "Bigfloaterline");
table.insert(rainboots.lure, "DentBigfloaterline");
table.insert(rainboots.lure, "FrogBigfloaterline");
table.insert(rainboots.lure, "RatBigfloaterline");
table.insert(rainboots.lure, "MouseBigfloaterline");
table.insert(rainboots.lure, "CrabBigfloaterline");
table.insert(rainboots.lure, "PejeBigfloaterline");
table.insert(rainboots.lure, "SmallDeepline");
table.insert(rainboots.lure, "DoughSmalldeepline");
table.insert(rainboots.lure, "FDoughSmalldeepline");
table.insert(rainboots.lure, "CricketSmalldeepline");
table.insert(rainboots.lure, "WormSmalldeepline");
table.insert(rainboots.lure, "RWormSmalldeepline");
table.insert(rainboots.lure, "GHopperSmalldeepline");
table.insert(rainboots.lure, "RoachSmalldeepline");
table.insert(rainboots.lure, "BfishSmalldeepline");
table.insert(rainboots.lure, "MediumDeepline");
table.insert(rainboots.lure, "PeachMediumdeepline");
table.insert(rainboots.lure, "DoughMediumdeepline");
table.insert(rainboots.lure, "FDoughMediumdeepline");
table.insert(rainboots.lure, "TurtleMediumdeepline");
table.insert(rainboots.lure, "HeavyDeepline");
table.insert(trashItems, rainboots);

-- local tube = {};
-- tube.item = "Base.Pipe";
-- tube.lure = {};
-- table.insert(tube.lure, "Mediumfloaterline");
-- table.insert(tube.lure, "WormMediumfloaterline");
-- table.insert(tube.lure, "DentMediumfloaterline");
-- table.insert(tube.lure, "RWormMediumfloaterline");
-- table.insert(tube.lure, "BfishMediumfloaterline");
-- table.insert(tube.lure, "RoachMediumfloaterline");
-- table.insert(tube.lure, "Bigfloaterline");
-- table.insert(tube.lure, "DentBigfloaterline");
-- table.insert(tube.lure, "FrogBigfloaterline");
-- table.insert(tube.lure, "RatBigfloaterline");
-- table.insert(tube.lure, "MouseBigfloaterline");
-- table.insert(tube.lure, "CrabBigfloaterline");
-- table.insert(tube.lure, "PejeBigfloaterline");
-- table.insert(tube.lure, "SmallDeepline");
-- table.insert(tube.lure, "DoughSmalldeepline");
-- table.insert(tube.lure, "FDoughSmalldeepline");
-- table.insert(tube.lure, "CricketSmalldeepline");
-- table.insert(tube.lure, "WormSmalldeepline");
-- table.insert(tube.lure, "RWormSmalldeepline");
-- table.insert(tube.lure, "GHopperSmalldeepline");
-- table.insert(tube.lure, "RoachSmalldeepline");
-- table.insert(tube.lure, "BfishSmalldeepline");
-- table.insert(tube.lure, "MediumDeepline");
-- table.insert(tube.lure, "DentMediumdeepline");
-- table.insert(tube.lure, "PejeMediumdeepline");
-- table.insert(tube.lure, "PeachMediumdeepline");
-- table.insert(tube.lure, "DoughMediumdeepline");
-- table.insert(tube.lure, "FDoughMediumdeepline");
-- table.insert(tube.lure, "HeavyDeepline");
-- table.insert(tube.lure, "AngHeavydeepline");
-- table.insert(tube.lure, "RatHeavydeepline");
-- table.insert(tube.lure, "MouseHeavydeepline");
-- table.insert(tube.lure, "FrogHeavydeepline");
-- table.insert(trashItems, tube);

local Hbox = {};
Hbox.item = "AdvancedFishing.HiddenBox";
Hbox.lure = {};
table.insert(Hbox.lure, "SilkMothCaterpillar");
table.insert(Hbox.lure, "SwallowtailCaterpillar");
table.insert(Hbox.lure, "MonarchCaterpillar");
table.insert(Hbox.lure, "AmericanLadyCaterpillar");
table.insert(Hbox.lure, "BandedWoolyBearCaterpillar");
table.insert(Hbox.lure, "Centipede");
table.insert(Hbox.lure, "Centipede2");
table.insert(Hbox.lure, "Maggots");
table.insert(Hbox.lure, "Millipede");
table.insert(Hbox.lure, "Millipede2");
table.insert(Hbox.lure, "Pillbug");
table.insert(Hbox.lure, "SawflyLarva");
table.insert(Hbox.lure, "Slug");
table.insert(Hbox.lure, "Slug2");
table.insert(Hbox.lure, "Snail");
table.insert(Hbox.lure, "Termites");
table.insert(Hbox.lure, "Worm");
table.insert(Hbox.lure, "RedWorm");
table.insert(Hbox.lure, "Cricket");
table.insert(Hbox.lure, "Grasshopper");
table.insert(Hbox.lure, "Cockroach");
table.insert(Hbox.lure, "BaitFish");
table.insert(Hbox.lure, "WturtlePiece");
table.insert(Hbox.lure, "Mediumfloaterline");
table.insert(Hbox.lure, "Bigfloaterline");
table.insert(Hbox.lure, "0Smallfloaterline");
table.insert(Hbox.lure, "StormFlutterstick");
table.insert(Hbox.lure, "SwimJig2");
table.insert(Hbox.lure, "SpoonLure3");
table.insert(Hbox.lure, "Spinnerbait");
table.insert(Hbox.lure, "RattlinRap");
table.insert(Hbox.lure, "SpoonLure1");
table.insert(Hbox.lure, "Spinnerbait");
table.insert(Hbox.lure, "SwimJig");
table.insert(Hbox.lure, "SwimJig3");
table.insert(Hbox.lure, "Crankbait");
table.insert(Hbox.lure, "SmallDeepline");
table.insert(Hbox.lure, "DoughSmalldeepline");
table.insert(Hbox.lure, "FDoughSmalldeepline");
table.insert(Hbox.lure, "CricketSmalldeepline");
table.insert(Hbox.lure, "WormSmalldeepline");
table.insert(Hbox.lure, "RWormSmalldeepline");
table.insert(Hbox.lure, "GHopperSmalldeepline");
table.insert(Hbox.lure, "RoachSmalldeepline");
table.insert(Hbox.lure, "BfishSmalldeepline");
table.insert(Hbox.lure, "MediumDeepline");
table.insert(Hbox.lure, "DentMediumdeepline");
table.insert(Hbox.lure, "PejeMediumdeepline");
table.insert(Hbox.lure, "PeachMediumdeepline");
table.insert(Hbox.lure, "DoughMediumdeepline");
table.insert(Hbox.lure, "FDoughMediumdeepline");
table.insert(Hbox.lure, "TurtleMediumdeepline");
table.insert(Hbox.lure, "AngMediumdeepline");
table.insert(Hbox.lure, "HeavyDeepline");
table.insert(Hbox.lure, "AngHeavydeepline");
table.insert(Hbox.lure, "RatHeavydeepline");
table.insert(Hbox.lure, "MouseHeavydeepline");
table.insert(Hbox.lure, "FrogHeavydeepline");
table.insert(trashItems, Hbox);

local Smallmetal = {};
Smallmetal.item = "AdvancedFishing.RustySmallSheetMetal";
Smallmetal.spearcatch = "no";
Smallmetal.lure = {};
table.insert(Smallmetal.lure, "MediumDeepline");
table.insert(Smallmetal.lure, "DentMediumdeepline");
table.insert(Smallmetal.lure, "PejeMediumdeepline");
table.insert(Smallmetal.lure, "PeachMediumdeepline");
table.insert(Smallmetal.lure, "DoughMediumdeepline");
table.insert(Smallmetal.lure, "FDoughMediumdeepline");
table.insert(Smallmetal.lure, "TurtleMediumdeepline");
table.insert(Smallmetal.lure, "AngMediumdeepline");
table.insert(Smallmetal.lure, "HeavyDeepline");
table.insert(Smallmetal.lure, "AngHeavydeepline");
table.insert(Smallmetal.lure, "RatHeavydeepline");
table.insert(Smallmetal.lure, "MouseHeavydeepline");
table.insert(Smallmetal.lure, "FrogHeavydeepline");
table.insert(trashItems, Smallmetal);

local Bigmetal = {};
Bigmetal.item = "AdvancedFishing.RustySheetMetal";
Bigmetal.spearcatch = "no";
Bigmetal.lure = {};
table.insert(Bigmetal.lure, "HeavyDeepline");
table.insert(Bigmetal.lure, "AngHeavydeepline");
table.insert(Bigmetal.lure, "RatHeavydeepline");
table.insert(Bigmetal.lure, "MouseHeavydeepline");
table.insert(Bigmetal.lure, "FrogHeavydeepline");
table.insert(trashItems, Bigmetal);

local Branch = {};
Branch.item = "Base.TreeBranch";
Branch.lure = {};
table.insert(Branch.lure, "HeavyDeepline");
table.insert(Branch.lure, "AngHeavydeepline");
table.insert(Branch.lure, "RatHeavydeepline");
table.insert(Branch.lure, "MouseHeavydeepline");
table.insert(Branch.lure, "FrogHeavydeepline");
table.insert(trashItems, Branch);

local Twigs = {};
Twigs.item = "Base.Twigs";
Twigs.lure = {};
table.insert(Twigs.lure, "Mediumfloaterline");
table.insert(Twigs.lure, "Bigfloaterline");
table.insert(Twigs.lure, "0Smallfloaterline");
table.insert(Twigs.lure, "StormFlutterstick");
table.insert(Twigs.lure, "SwimJig2");
table.insert(Twigs.lure, "SpoonLure3");
table.insert(Twigs.lure, "Spinnerbait");
table.insert(Twigs.lure, "RattlinRap");
table.insert(Twigs.lure, "SpoonLure1");
table.insert(Twigs.lure, "Spinnerbait");
table.insert(Twigs.lure, "SwimJig");
table.insert(Twigs.lure, "SwimJig3");
table.insert(Twigs.lure, "Crankbait");
table.insert(Twigs.lure, "SmallDeepline");
table.insert(Twigs.lure, "DoughSmalldeepline");
table.insert(Twigs.lure, "FDoughSmalldeepline");
table.insert(Twigs.lure, "CricketSmalldeepline");
table.insert(Twigs.lure, "WormSmalldeepline");
table.insert(Twigs.lure, "RWormSmalldeepline");
table.insert(Twigs.lure, "GHopperSmalldeepline");
table.insert(Twigs.lure, "RoachSmalldeepline");
table.insert(Twigs.lure, "BfishSmalldeepline");
table.insert(Twigs.lure, "MediumDeepline");
table.insert(Twigs.lure, "DentMediumdeepline");
table.insert(Twigs.lure, "PejeMediumdeepline");
table.insert(Twigs.lure, "PeachMediumdeepline");
table.insert(Twigs.lure, "DoughMediumdeepline");
table.insert(Twigs.lure, "FDoughMediumdeepline");
table.insert(Twigs.lure, "TurtleMediumdeepline");
table.insert(Twigs.lure, "AngMediumdeepline");
table.insert(trashItems, Twigs);

-- testing hook --
local testhook = {};
testhook.item = "GoldenHook";
testhook.plastic = true;
testhook.chanceOfBreak = 1;
lure["GoldenHook"] = testhook;
--------------------- Propiedades de señuelos -----------------------

local AFFT1 = {};
AFFT1.item = "StormFlutterstick";
AFFT1.plastic = true;
AFFT1.chanceOfBreak = 1;
lure["StormFlutterstick"] = AFFT1;

local AFFT2 = {};
AFFT2.item = "RattlinRap";
AFFT2.plastic = true;
AFFT2.chanceOfBreak = 1;
lure["RattlinRap"] = AFFT2;

local AFFT3 = {};
AFFT3.item = "SwimJig";
AFFT3.plastic = true;
AFFT3.chanceOfBreak = 1;
lure["SwimJig"] = AFFT3;

local AFFT4 = {};
AFFT4.item = "SwimJig2";
AFFT4.plastic = true;
AFFT4.chanceOfBreak = 1;
lure["SwimJig2"] = AFFT4;

local AFFT5 = {};
AFFT5.item = "SwimJig3";
AFFT5.plastic = true;
AFFT5.chanceOfBreak = 1;
lure["SwimJig3"] = AFFT5;

local AFFT6 = {};
AFFT6.item = "SpoonLure1";
AFFT6.plastic = true;
AFFT6.chanceOfBreak = 1;
lure["SpoonLure1"] = AFFT6;

local AFFT7 = {};
AFFT7.item = "SpoonLure2";
AFFT7.plastic = true;
AFFT7.chanceOfBreak = 1;
lure["SpoonLure2"] = AFFT7;

local AFFT8 = {};
AFFT8.item = "SpoonLure3";
AFFT8.plastic = true;
AFFT8.chanceOfBreak = 1;
lure["SpoonLure3"] = AFFT8;

local AFFT9 = {};
AFFT9.item = "GTPopper";
AFFT9.plastic = true;
AFFT9.chanceOfBreak = 1;
lure["GTPopper"] = AFFT9;

local AFFT10 = {};
AFFT10.item = "JitterBug";
AFFT10.plastic = true;
AFFT10.chanceOfBreak = 1;
lure["JitterBug"] = AFFT10;

local AFFT11 = {};
AFFT11.item = "Crankbait";
AFFT11.plastic = true;
AFFT11.chanceOfBreak = 1;
lure["Crankbait"] = AFFT11;

local AFFT12 = {};
AFFT12.item = "SwimShad";
AFFT12.plastic = true;
AFFT12.chanceOfBreak = 1;
lure["SwimShad"] = AFFT12;

local AFFT13 = {};
AFFT13.item = "Alfers";
AFFT13.plastic = true;
AFFT13.chanceOfBreak = 1;
lure["Alfers"] = AFFT13;

local AFFT14 = {};
AFFT14.item = "Spinnerbait";
AFFT14.plastic = true;
AFFT14.chanceOfBreak = 1;
lure["Spinnerbait"] = AFFT14;

-- Lineas sin carnada
local AFC0 = {};
AFC0.item = "0Smallfloaterline";
AFC0.plastic = true;
AFC0.chanceOfBreak = 15;
lure["0Smallfloaterline"] = AFC0;

local AFC1 = {};
AFC1.item = "Mediumfloaterline";
AFC1.plastic = true;
AFC1.chanceOfBreak = 15;
lure["Mediumfloaterline"] = AFC1;

local AFBC = {};
AFBC.item = "Bigfloaterline";
AFBC.plastic = true;
AFBC.chanceOfBreak = 15;
lure["Bigfloaterline"] = AFBC;

local AFLF = {};
AFLF.item = "SmallDeepline";
AFLF.plastic = true;
AFLF.chanceOfBreak = 60;
lure["SmallDeepline"] = AFLF;

local AFLF2 = {};
AFLF2.item = "MediumDeepline";
AFLF2.plastic = true;
AFLF2.chanceOfBreak = 50;
lure["MediumDeepline"] = AFLF2;

local AFLF3 = {};
AFLF3.item = "HeavyDeepline";
AFLF3.plastic = true;
AFLF3.chanceOfBreak = 40;
lure["HeavyDeepline"] = AFLF3;

-- Carnadas
local AFC1 = {};
AFC1.item = "FishingDough";
AFC1.plastic = false;
AFC1.chanceOfBreak = 70;
lure["FishingDough"] = AFC1;

local AFC2 = {};
AFC2.item = "StrongFishingDough";
AFC2.plastic = false;
AFC2.chanceOfBreak = 50;
lure["StrongFishingDough"] = AFC2;

local AFC3 = {};
AFC3.item = "WturtlePiece";
AFC3.plastic = false;
AFC3.chanceOfBreak = 60;
lure["WturtlePiece"] = AFC3;

local AFC4 = {};
AFC4.item = "Anguila";
AFC4.plastic = false;
AFC4.chanceOfBreak = 40;
lure["Anguila"] = AFC4;

-- Lineas boya chica
local AFL2 = {};
AFL2.item = "DoughSmallfloaterline";
AFL2.plastic = false;
AFL2.chanceOfBreak = 20;
lure["DoughSmallfloaterline"] = AFL2;

local AFL3 = {};
AFL3.item = "FDoughSmallfloaterline";
AFL3.plastic = false;
AFL3.chanceOfBreak = 10;
lure["FDoughSmallfloaterline"] = AFL3;

local AFL4 = {};
AFL4.item = "CricketSmallfloaterline";
AFL4.plastic = false;
AFL4.chanceOfBreak = 8;
lure["CricketSmallfloaterline"] = AFL4;

local AFL5 = {};
AFL5.item = "WormSmallfloaterline";
AFL5.plastic = false;
AFL5.chanceOfBreak = 8;
lure["WormSmallfloaterline"] = AFL5;

local AFL6 = {};
AFL6.item = "GHopperSmallfloaterline";
AFL6.plastic = false;
AFL6.chanceOfBreak = 8;
lure["GHopperSmallfloaterline"] = AFL6;

local AFL7 = {};
AFL7.item = "RoachSmallfloaterline";
AFL7.plastic = false;
AFL7.chanceOfBreak = 8;
lure["RoachSmallfloaterline"] = AFL7;

local AFL8 = {};
AFL8.item = "BfishSmallfloaterline";
AFL8.plastic = false;
AFL8.chanceOfBreak = 2;
lure["BfishSmallfloaterline"] = AFL8;

local AFL9 = {};
AFL9.item = "RWormSmallfloaterline";
AFL9.plastic = false;
AFL9.chanceOfBreak = 8;
lure["RWormSmallfloaterline"] = AFL9;

-- Lineas boya mediana
local AFLM1 = {};
AFLM1 .item = "DoughMediumfloaterline";
AFLM1 .plastic = false;
AFLM1 .chanceOfBreak = 8;
lure["DoughMediumfloaterline"] = AFLM1;

local AFLM2 = {};
AFLM2.item = "FDoughMediumfloaterline";
AFLM2.plastic = false;
AFLM2.chanceOfBreak = 10;
lure["FDoughMediumfloaterline"] = AFLM2;

local AFLM3 = {};
AFLM3.item = "CricketMediumfloaterline";
AFLM3.plastic = false;
AFLM3.chanceOfBreak = 8;
lure["CricketMediumfloaterline"] = AFLM3;

local AFLM4 = {};
AFLM4.item = "WormMediumfloaterline";
AFLM4.plastic = false;
AFLM4.chanceOfBreak = 8;
lure["WormMediumfloaterline"] = AFLM4;

local AFLM5 = {};
AFLM5.item = "GHopperMediumfloaterline";
AFLM5.plastic = false;
AFLM5.chanceOfBreak = 8;
lure["GHopperMediumfloaterline"] = AFLM5;

local AFLM6 = {};
AFLM6.item = "RoachMediumfloaterline";
AFLM6.plastic = false;
AFLM6.chanceOfBreak = 8;
lure["RoachMediumfloaterline"] = AFLM6;

local AFLM7 = {};
AFLM7.item = "BfishMediumfloaterline";
AFLM7.plastic = false;
AFLM7.chanceOfBreak = 2;
lure["BfishMediumfloaterline"] = AFLM7;

local AFLM8 = {};
AFLM8.item = "RWormMediumfloaterline";
AFLM8.plastic = false;
AFLM8.chanceOfBreak = 8;
lure["RWormMediumfloaterline"] = AFLM8;

local AFLM9 = {};
AFLM9.item = "DentMediumfloaterline";
AFLM9.plastic = false;
AFLM9.chanceOfBreak = 8;
lure["DentMediumfloaterline"] = AFLM9;

local AFLM10 = {};
AFLM10.item = "AngMediumfloaterline";
AFLM10.plastic = false;
AFLM10.chanceOfBreak = 8;
lure["AngMediumfloaterline"] = AFLM10;

-- Lineas boya grande

local AFLG1 = {};
AFLG1.item = "DentBigfloaterline";
AFLG1.plastic = false;
AFLG1.chanceOfBreak = 8;
lure["DentBigfloaterline"] = AFLG1;

local AFLG2 = {};
AFLG2.item = "FrogBigfloaterline";
AFLG2.plastic = false;
AFLG2.chanceOfBreak = 8;
lure["FrogBigfloaterline"] = AFLG2;

local AFLG3 = {};
AFLG3.item = "RatBigfloaterline";
AFLG3.plastic = false;
AFLG3.chanceOfBreak = 8;
lure["RatBigfloaterline"] = AFLG3;

local AFLG4 = {};
AFLG4.item = "MouseBigfloaterline";
AFLG4.plastic = false;
AFLG4.chanceOfBreak = 8;
lure["MouseBigfloaterline"] = AFLG4;

local AFLG5 = {};
AFLG5.item = "CrabBigfloaterline";
AFLG5.plastic = false;
AFLG5.chanceOfBreak = 8;
lure["CrabBigfloaterline"] = AFLG5;

local AFLG6 = {};
AFLG6.item = "PejeBigfloaterline";
AFLG6.plastic = false;
AFLG6.chanceOfBreak = 8;
lure["PejeBigfloaterline"] = AFLG6;

local AFLG7 = {};
AFLG7.item = "AngBigfloaterline";
AFLG7.plastic = false;
AFLG7.chanceOfBreak = 8;
lure["AngBigfloaterline"] = AFLG7;

-- Lineas de fondo chica

local AFLFC1 = {};
AFLFC1.item = "DoughSmalldeepline";
AFLFC1.plastic = false;
AFLFC1.chanceOfBreak = 8;
lure["DoughSmalldeepline"] = AFLFC1;

local AFLFC2 = {};
AFLFC2.item = "FDoughSmalldeepline";
AFLFC2.plastic = false;
AFLFC2.chanceOfBreak = 5;
lure["FDoughSmalldeepline"] = AFLFC2;

local AFLFC3 = {};
AFLFC3.item = "CricketSmalldeepline";
AFLFC3.plastic = false;
AFLFC3.chanceOfBreak = 8;
lure["CricketSmalldeepline"] = AFLFC3;

local AFLFC4 = {};
AFLFC4.item = "WormSmalldeepline";
AFLFC4.plastic = false;
AFLFC4.chanceOfBreak = 8;
lure["WormSmalldeepline"] = AFLFC4;

local AFLFC5 = {};
AFLFC5.item = "RWormSmalldeepline";
AFLFC5.plastic = false;
AFLFC5.chanceOfBreak = 8;
lure["RWormSmalldeepline"] = AFLFC5;

local AFLFC6 = {};
AFLFC6.item = "GHopperSmalldeepline";
AFLFC6.plastic = false;
AFLFC6.chanceOfBreak = 8;
lure["GHopperSmalldeepline"] = AFLFC6;

local AFLFC7 = {};
AFLFC7.item = "RoachSmalldeepline";
AFLFC7.plastic = false;
AFLFC7.chanceOfBreak = 8;
lure["RoachSmalldeepline"] = AFLFC7;

local AFLFC8 = {};
AFLFC8.item = "BfishSmalldeepline";
AFLFC8.plastic = false;
AFLFC8.chanceOfBreak = 8;
lure["BfishSmalldeepline"] = AFLFC8;

-- Lineas de fondo mediana

local AFLFM1 = {};
AFLFM1.item = "DentMediumdeepline";
AFLFM1.plastic = false;
AFLFM1.chanceOfBreak = 5;
lure["DentMediumdeepline"] = AFLFM1;

local AFLFM2 = {};
AFLFM2.item = "PejeMediumdeepline";
AFLFM2.plastic = false;
AFLFM2.chanceOfBreak = 5;
lure["PejeMediumdeepline"] = AFLFM2;

local AFLFM3 = {};
AFLFM3.item = "PeachMediumdeepline";
AFLFM3.plastic = false;
AFLFM3.chanceOfBreak = 5;
lure["PeachMediumdeepline"] = AFLFM3;

local AFLFM4 = {};
AFLFM4.item = "DoughMediumdeepline";
AFLFM4.plastic = false;
AFLFM4.chanceOfBreak = 5;
lure["DoughMediumdeepline"] = AFLFM4;

local AFLFM5 = {};
AFLFM5.item = "FDoughMediumdeepline";
AFLFM5.plastic = false;
AFLFM5.chanceOfBreak = 3;
lure["FDoughMediumdeepline"] = AFLFM5;

local AFLFM6 = {};
AFLFM6.item = "TurtleMediumdeepline";
AFLFM6.plastic = false;
AFLFM6.chanceOfBreak = 5;
lure["TurtleMediumdeepline"] = AFLFM6;

local AFLFM7 = {};
AFLFM7.item = "AngMediumdeepline";
AFLFM7.plastic = false;
AFLFM7.chanceOfBreak = 5;
lure["AngMediumdeepline"] = AFLFM7;

-- Lineas de fondo grande

local AFLFG1 = {};
AFLFG1.item = "AngHeavydeepline";
AFLFG1.plastic = false;
AFLFG1.chanceOfBreak = 3;
lure["AngHeavydeepline"] = AFLFG1;
Fishing.lure = lure

local AFLFG2 = {};
AFLFG2.item = "RatHeavydeepline";
AFLFG2.plastic = false;
AFLFG2.chanceOfBreak = 3;
lure["RatHeavydeepline"] = AFLFG2;
Fishing.lure = lure

local AFLFG3 = {};
AFLFG3.item = "FrogHeavydeepline";
AFLFG3.plastic = false;
AFLFG3.chanceOfBreak = 3;
lure["FrogHeavydeepline"] = AFLFG3;
Fishing.lure = lure

local AFLFG4 = {};
AFLFG4.item = "MouseHeavydeepline";
AFLFG4.plastic = false;
AFLFG4.chanceOfBreak = 3;
lure["MouseHeavydeepline"] = AFLFG4;
Fishing.lure = lure

local redworm = {};
redworm.item = "RedWorm";
redworm.plastic = false;
redworm.chanceOfBreak = 15;
lure["RedWorm"] = redworm;